name: Setup Audio Dependencies

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2022

    env:
      Platform: x64
      Configuration: Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Download and Setup libogg
        run: |
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/ogg/libogg-1.3.5.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libogg-1.3.5 libogg
          cd ./dependencies/windows/libogg/win32/VS2015
          msbuild libogg_static.sln /p:Configuration=Release /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:TargetName=libogg_static
          cd ../../../../..

      - name: Download and Setup libvorbis
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libvorbis-1.3.7 libvorbis
          cd ./dependencies/windows/libvorbis/win32/VS2010
          msbuild vorbis_static.sln /p:Configuration=Release /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:TargetName=libvorbis_static
          cd ../../../../..

      - name: Download and Setup libtheora
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-1.2.0alpha1.zip" -OutFile "libtheora.zip"
          Expand-Archive -Path libtheora.zip -DestinationPath ./dependencies/windows/
          Rename-Item ./dependencies/windows/libtheora-1.2.0alpha1 libtheora
          cd ./dependencies/windows/libtheora/win32/VS2010
          msbuild libtheora_static.sln /p:Configuration=Release /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:AdditionalIncludeDirectories="$(System.IO.Path::Combine($(System.IO.Directory::GetCurrentDirectory()), '..', '..', 'libvorbis', 'include'));$(System.IO.Path::Combine($(System.IO.Directory::GetCurrentDirectory()), '..', '..', 'libogg', 'include'))"
          cd ../../../../..

      - name: Archive Built Libraries
        run: |
          mkdir built_libraries
          xcopy /S /Y .\dependencies\windows\libogg\win32\VS2015\Release\*.lib .\built_libraries\
          xcopy /S /Y .\dependencies\windows\libvorbis\win32\VS2010\Release\*.lib .\built_libraries\
          xcopy /S /Y .\dependencies\windows\libtheora\win32\VS2010\Release\*.lib .\built_libraries\
          powershell Compress-Archive -Path .\built_libraries\* -DestinationPath built_libraries.zip

      - name: Upload Built Libraries
        uses: actions/upload-artifact@v2
        with:
          name: built-libraries
          path: built_libraries.zip
