name: Setup Audio Dependencies with MSYS2

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MSYS2
        run: choco install msys2 -y

      - name: Update MSYS2 and install dependencies
        run: |
          C:\tools\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
          C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-make wget unzip"

      - name: Download and Setup libogg
        run: |
          C:\tools\msys64\usr\bin\bash -lc "wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.zip -O libogg.zip"
          C:\tools\msys64\usr\bin\bash -lc "unzip libogg.zip -d ./libogg"
          C:\tools\msys64\usr\bin\bash -lc "cd libogg/libogg-1.3.5 && ./configure --prefix=/mingw64 && make && make install"

      - name: Download and Setup libvorbis
        run: |
          C:\tools\msys64\usr\bin\bash -lc "wget https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip -O libvorbis.zip"
          C:\tools\msys64\usr\bin\bash -lc "unzip libvorbis.zip -d ./libvorbis"
          C:\tools\msys64\usr\bin\bash -lc "cd libvorbis/libvorbis-1.3.7 && ./configure --prefix=/mingw64 && make && make install"

      - name: Download and Setup libtheora
        run: |
          C:\tools\msys64\usr\bin\bash -lc "wget https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-1.2.0alpha1.zip -O libtheora.zip"
          C:\tools\msys64\usr\bin\bash -lc "unzip libtheora.zip -d ./libtheora"
          C:\tools\msys64\usr\bin\bash -lc "cd libtheora/libtheora-1.2.0alpha1 && ./configure --prefix=/mingw64 && make && make install"

      - name: Archive Built Libraries
        run: |
          C:\tools\msys64\usr\bin\bash -lc "mkdir -p built_libraries"
          C:\tools\msys64\usr\bin\bash -lc "cp /mingw64/lib/*.a built_libraries/"
          C:\tools\msys64\usr\bin\bash -lc "cp /mingw64/lib/*.la built_libraries/"
          C:\tools\msys64\usr\bin\bash -lc "zip -r built_libraries.zip built_libraries/"

      - name: Upload Built Libraries
        uses: actions/upload-artifact@v2
        with:
          name: built-libraries
          path: built_libraries.zip
