name: Setup Audio Dependencies with MinGW-w64

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MinGW-w64 and wget
        run: |
          choco install mingw -y
          choco install wget -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

      - name: Add MinGW to PATH
        run: echo 'C:\tools\mingw64\bin' >> $env:GITHUB_PATH

      - name: Download and Setup libogg
        shell: bash
        run: |
          wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.zip -O libogg.zip
          unzip libogg.zip -d ./libogg
          cd libogg/libogg-1.3.5
          ./configure --prefix=/usr/local
          make
          make install

      - name: Download and Setup libvorbis
        shell: bash
        run: |
          wget https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip -O libvorbis.zip
          unzip libvorbis.zip -d ./libvorbis
          cd libvorbis/libvorbis-1.3.7
          ./configure --prefix=/usr/local
          make
          make install

      - name: Download and Setup libtheora
        shell: bash
        run: |
          wget https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-1.2.0alpha1.zip -O libtheora.zip
          unzip libtheora.zip -d ./libtheora
          cd libtheora/libtheora-1.2.0alpha1
          ./configure --prefix=/usr/local
          make
          make install

      - name: Archive Built Libraries
        shell: bash
        run: |
          mkdir -p built_libraries
          cp /usr/local/lib/*.a built_libraries/
          cp /usr/local/lib/*.la built_libraries/
          zip -r built_libraries.zip built_libraries/

      - name: Upload Built Libraries
        uses: actions/upload-artifact@v2
        with:
          name: built-libraries
          path: built_libraries.zip
