name: Setup Audio Dependencies with MinGW-w64

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MinGW-w64
        run: |
          choco install mingw -y
          refreshenv

      - name: Add MinGW to PATH
        run: echo "::add-path::C:\tools\mingw64\bin"

      - name: Download and Setup libogg
        run: |
          Invoke-WebRequest -Uri "https://downloads.xiph.org/releases/ogg/libogg-1.3.5.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./libogg
          cd libogg/libogg-1.3.5
          ./configure --prefix=/usr/local
          make
          make install

      - name: Download and Setup libvorbis
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./libvorbis
          cd libvorbis/libvorbis-1.3.7
          ./configure --prefix=/usr/local
          make
          make install

      - name: Download and Setup libtheora
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-1.2.0alpha1.zip" -OutFile "libtheora.zip"
          Expand-Archive -Path libtheora.zip -DestinationPath ./libtheora
          cd libtheora/libtheora-1.2.0alpha1
          ./configure --prefix=/usr/local
          make
          make install

      - name: Archive Built Libraries
        run: |
          mkdir -p built_libraries
          cp /usr/local/lib/*.a built_libraries/
          cp /usr/local/lib/*.la built_libraries/
          powershell Compress-Archive -Path built_libraries/* -DestinationPath built_libraries.zip

      - name: Upload Built Libraries
        uses: actions/upload-artifact@v2
        with:
          name: built-libraries
          path: built_libraries.zip
