name: iOS App CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          submodules: recursive
          
    - name: Install dependencies
      run: brew install ldid

    - name: Build the app for simulator
      run: xcodebuild -workspace RSDKv5.xcodeproj/project.xcworkspace -scheme RSDKv5 -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' clean build

    - name: Run tests
      run: xcodebuild test -workspace RSDKv5.xcodeproj/project.xcworkspace -scheme RSDKv5 -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
      
    - name: Build for device
      run: xcodebuild -workspace RSDKv5.xcodeproj/project.xcworkspace -scheme RSDKv5 -sdk iphoneos -configuration Release clean build

    - name: Fakesign app
      run: ldid -S path/to/RSDKv5.app/RSDKv5
    
    - name: Convert to IPA
      run: |
        mkdir -p Payload
        cp -r path/to/RSDKv5.app Payload/
        zip -r RSDKv5.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RSDKv5.ipa
        path: RSDKv5.ipa
