name: iOS App CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Checkout submodules recursively

    - name: Install dependencies
      run: |
        brew install ldid

    - name: Update deployment target
      run: |
        find . -name "*.xcodeproj" -print -exec /usr/libexec/PlistBuddy -c "Set :\"Build settings\":\"IPHONEOS_DEPLOYMENT_TARGET\" 12.0" {}/project.pbxproj \;

    - name: Build the app for simulator
      run: |
        xcodebuild -workspace RSDKv5.xcodeproj/project.xcworkspace \
                   -scheme RSDKv5 \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 12' \
                   clean build \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   AD_HOC_CODE_SIGNING_ALLOWED=YES

    - name: Run tests
      run: |
        xcodebuild test -workspace RSDKv5.xcodeproj/project.xcworkspace \
                   -scheme RSDKv5 \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 12' \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   AD_HOC_CODE_SIGNING_ALLOWED=YES

    - name: Build for device
      run: |
        xcodebuild -workspace RSDKv5.xcodeproj/project.xcworkspace \
                   -scheme RSDKv5 \
                   -sdk iphoneos \
                   -configuration Release \
                   clean build \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   AD_HOC_CODE_SIGNING_ALLOWED=YES \
                   DEVELOPMENT_TEAM=XYZ0123456 \
                   ORG_IDENTIFIER=com.SideStore \
                   DWARF_DSYM_FOLDER_PATH="."

    - name: Fakesign app
      run: ldid -S path/to/RSDKv5.app/RSDKv5
    
    - name: Convert to IPA
      run: |
        mkdir -p Payload
        cp -r path/to/RSDKv5.app Payload/
        zip -r RSDKv5.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RSDKv5.ipa
        path: RSDKv5.ipa
