name: Build Sonic Mania Decompilation

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; 
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install git -y

    - name: Setup vcpkg
      run: |
        if not exist vcpkg (
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
        )
    
    - name: Install Libraries with vcpkg
      run: .\vcpkg\vcpkg.exe install libtheora libogg --triplet=x64-windows-static

    - name: Clone Sonic-Mania-Decompilation
      run: |
        if exist Sonic-Mania-Decompilation (
          cd Sonic-Mania-Decompilation
          git submodule update --init --recursive
          cd ..\
        ) else (
          git clone --recursive https://github.com/RSDKModding/Sonic-Mania-Decompilation
        )
    
    - name: Configure for compiling
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static
      working-directory: ./Sonic-Mania-Decompilation

    - name: Compile the game
      run: cmake --build build --config release
      working-directory: ./Sonic-Mania-Decompilation

    - name: Prepare artifacts
      run: |
        mkdir DECOMP
        copy TEMP/Sonic-Mania-Decompilation/build/dependencies/RSDKv5/Release/RSDKv5u.exe DECOMP/
        copy TEMP/Sonic-Mania-Decompilation/build/dependencies/RSDKv5/Release/Game.dll DECOMP/
        # Assume Data.rsdk or Data folder is already present in the repository or acquired elsewhere
        # copy path/to/Data.rsdk DECOMP/ OR copy path/to/Data DECOMP/
    
    - name: Zip artifacts
      run: powershell Compress-Archive -Path DECOMP/* -DestinationPath DECOMP.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sonic-mania-decompilation
        path: DECOMP.zip
